[project]
name = "try-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vivek", email = "vivekrajraghav@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "uvicorn>=0.53.0",
]

[project.scripts]
try-fastapi = "try_fastapi:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
